server:
  port: 6001
spring:
  redis:
    database: 0
    host: 125.64.43.53
    port: 10001
    password: M9Ncehx92#$Redis
swagger:
  package: com.zxw.authentication
  basic:
    ##设置帐号与密码
    enable: true
    username: admin
    password: 123
#cas:
#  server-login-url: https://localhost:8443/cas/login
#  server-url-prefix: https://localhost:8443/cas
#  client-host-url: http://127.0.0.1:6001/
#  validation-type: cas3
