server:
  port:  53020
feign:
  compression:
    request:
      enabled: true
      mime-types: ["text/xml","application/xml","application/json"]
      min-request-size: 2048
    response:
      enabled: true
      useGzipDecoder: true
  okhttp:
    enabled: true
  httpclient:
    enabled: true
spring:
  application:
    name: authorization
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    root: debug
