spring:
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://125.64.5.82:23306/bizeispacttest?characterEncoding=utf8&useSSL=true&serverTimezone=Hongkong&nullNamePatternMatchesAll=true
  password: 940084zxw
  username: root
mybatis-plus:
  type-aliases-package: com.example.demo.entity.dos

