server:
  port: 53022
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: auth
          uri: lb://authorization
          predicates:
            - Path=/oauth/**
        - id: order
          uri: lb://resourceOrder
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1