##########headless与sts,命令:cat <<EOF | kubectl create -f - 中间是复制下面的命令，最后一排EOF
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
spec:
  selector:
    app: mysql
  clusterIP: None #和svc的区别
  ports:
    - name: mysql-port
      port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
              readOnly: false
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
      volumes:
        - name: mysql-data
          hostPath:
            path: /opt/k8s/mysql
            type: DirectoryOrCreate
