pipeline{
	agent any

	stages{
		stage('拉取代码'){
			steps{
				checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/yuanwangzxw/zdemo.git']]])
			}
		}

		stage('编绎构建'){
			steps{
				sh label: '', script: 'mvn -f authentication clean install -Dmaven.test.skip=true dockerfile:build'
			}
		}

		stage('上传镜像'){
            steps{
                sh label: '', script: 'docker tag authentication:0.0.1-SNAPSHOT 192.168.56.101:80/test/authentication:0.0.1-SNAPSHOT
                 && docker login -u root -p Harbor12345 192.168.56.101 && docker push 192.168.56.101:80/test/authentication:0.0.1-SNAPSHOT
                 && docker rmi -f authentication:0.0.1-SNAPSHOT'
            }
        }

	}
}
